---
title: "Research"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Publications
***

### The Effect of Fraternity Moratoriums on Alcohol Offenses and Sexual Assaults

**Pre-print draft [here](https://github.com/michaeltopper1/Fraternities/blob/master/paper_iterations/accepted_paper/main.pdf).**

**Journal link [here](https://jhr.uwpress.org/content/early/2023/05/01/jhr.0722-12422R1).**

*Journal of Human Resources*

*Abstract*: 
I exploit variation in timing from 44 temporary university-wide halts on all fraternity activity with alcohol (*moratoriums*) across 37 universities over 2014-2019. I construct a novel data set, merging incident-level crime logs from university police departments to provide the first causal estimates of the effect of moratoriums on reports of alcohol offenses and sexual assaults. In particular, I find robust evidence that moratoriums decrease alcohol offenses by 26%. Additionally, I find suggestive evidence that moratoriums decrease reports of sexual assault on the weekends by 29%. However, I do not find evidence of long-term changes once the moratorium is lifted.


### The Unintended Consequences of Policing Technology: Evidence from ShotSpotter (with Toshio Ferrazares)

**Previously circulated as The Effect of ShotSpotter Technology on Police Response Times**

**Forthcoming**: *Journal of Human Resources*

*Abstract:*
Technology is integral to police departments, automating officer tasks, but inherently changing their time allocation. We investigate this by studying ShotSpotter, a technology that automates gunfire detection. Following a detection, officers are dispatched to the scene, thereby reallocating their time. We leverage this shock to officers’ time allocation using the rollout of ShotSpotter across Chicago police districts to study the effects on 911 call response. We find substantial consequences---officers are dispatched to calls slower (23%), arrive on-scene later (13%), and the probability of arrest is decreased 9%. Consequently, police departments must evaluate their resource capacities prior to implementing technologies.

*In the Press:* [The Economist](https://www.economist.com/united-states/2023/12/27/americas-new-policing-tech-isnt-cutting-crime?giftId=77056dba-6af1-40be-af4c-0f6e5baf028b), [The Chicago Tribune](https://www.chicagotribune.com/2024/03/03/with-shotspotter-staying-in-chicago-for-the-time-being-dispute-continues-over-the-systems-usefulness/),   [Stateline](https://stateline.org/2024/02/27/chicago-is-the-latest-city-rethinking-disputed-technology-that-listens-for-gunshots/),
[NPR](https://www.npr.org/2024/10/20/nx-s1-5131546/researchers-are-skeptical-of-this-gunfire-detection-system-chicago-no-longer-uses-it),
[WBEZ Chicago](https://www.wbez.org/2024/09/18/research-finds-shotspotter-slows-police-responses-to-911-calls), [Block Club Chicago](https://blockclubchicago.org/2024/10/08/south-side-officials-raise-2-5-million-in-effort-to-keep-shotspotter-in-chicago/)



## Works in Progress

### Police Efficiency and Discretion: Learn-by-Doing
**Draft available upon request**

I leverage the quasi-random variation in police officers' exposure to field training tasks to examine how the allocation of training experiences affects worker efficiency and discretion. Using a novel dataset linking Chicago Police Department dispatches with officers' field training records, I find that officers who receive high task-specific training exposure complete similar assignments faster (~2%) and make fewer arrests (~3.3%) in their first year on the job. These effects are driven by routine, low-priority incidents, persist over time, and differ across skills. Together, these findings suggest that organizational performance can be improved with a reallocation of existing on-the-job training.

### Gunshot Noise and Birth Outcomes (with Anna Jaskiewicz)

Gun violence is ubiquitous across the United States, with gun-related deaths reaching an all-time high in 2021. The prevalence of gunfire results in loud and potentially stress-inducing sounds, which may adversely affect critical stages of in-utero development. However, gunfire is largely unreported, creating a unique challenge for researchers to understand its consequences. In this paper, we mitigate this shortcoming by leveraging data from ShotSpotter—an acoustic gunshot technology which uses an array of sensors placed on city structures to detect the sound of gunfire. We combine this unique data source with the universe of births in San Francisco over a four-year period (2016-2020), each matched to a mother's residence. Using the variation in gunfire detections from ShotSpotter at the census-block level, we employ a difference-in-differences methodology and find that gunshot noise creates substantial decreases in gestation lengths, resulting in an increase in preterm deliveries. These effects are driven entirely by times of the day when civilians are awake, and are particularly concentrated among mothers with low levels of education. These results suggest that gunshot noise is a major factor contributing to the income inequities in pregnancy outcomes.

### Police Shift Changes and Use-of-Force (with Toshio Ferrazares)

*Stay Tuned for Updates*

### Reduce Barriers, Increase Diversity, and Maintain Quality

*Stay Tuned for Updates*

### The Stock and Flows of Police Hiring (with Toshio Ferrazares)

*Draft Coming Soon*


### Untitled ShotSpotter Validation Project (with Taylor Wright)

*Stay Tuned for Updates*



