---
title: "Teaching"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Instructor of Record
***
* Economics 102 - Introductory Microeconomics *(San Diego State University)*
  + See how students evaluated my course on [ratemyprofessors](https://www.ratemyprofessors.com/ShowRatings.jsp?tid=2280144).
* Econ 199RA - Data Hack 2022 *(University of California, Santa Barbara)*

## Teaching Assistant
***
* Economics 145 - Data Wrangling in Economics *(University of California, Santa Barbara)*
* Economics 140A - Introductory Econometrics I *(University of California, Santa Barbara)*
* Economics 140B - Introductory Econometrics II *(University of California, Santa Barbara)*
* Economics 1 - Introductory Microeconomics *(University of California, Santa Barbara)*
* Economics 2 - Introductory Macroeconomics *(University of California, Santa Barbara)*
* Economics 10A - Intermediate Microeconomic Theory *(University of California, Santa Barbara)*
* INT 93LS- Introduction to Research in STEM, Humanities, and Social Sciences *(University of California, Santa Barbara)*
* Econonmics 102 - Introductory Microeconomics *(San Diego State University)*
* Econonmics 441 - Introduction to Econometrics *(San Diego State University)*